version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-testdb}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres} -d ${DB_NAME:-testdb}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      # Build a DATABASE_URL that points to the `db` service inside compose network.
      # Use DB_HOST/DB_PORT so values are explicit and easier to override for local vs compose runs.
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DATABASE_URL: "postgres://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@${DB_HOST:-db}:${DB_PORT:-5432}/${DB_NAME:-testdb}"
      DATABASE_SSL: ${DATABASE_SSL:-false}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${PORT:-3000}
      RESET_TOKEN_EXPIRY_MINUTES: ${RESET_TOKEN_EXPIRY_MINUTES:-30}
      SALT_ROUNDS: ${SALT_ROUNDS:-12}
      PG_MAX_CLIENTS: ${PG_MAX_CLIENTS:-10}
      PG_IDLE_TIMEOUT_MS: ${PG_IDLE_TIMEOUT_MS:-30000}
      PG_CONN_TIMEOUT_MS: ${PG_CONN_TIMEOUT_MS:-2000}
    ports:
      - "${PORT:-3000}:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
